import { Octokit } from '@octokit/rest';
import { VCSPlugin, PullRequest, PlanFileResult, VCSProjectConfig } from '../base';
import { getErrorMessage } from '../../types/errors';
import { logger } from '../../logger';

/**
 * GitHub VCS plugin using Octokit
 * Supports Personal Access Tokens and GitHub Apps
 */
export class GitHubVCS implements VCSPlugin {
  id = 'github';
  type = 'github' as const;

  // Plan file support
  supportsPlanFiles = true;

  private octokit: Octokit;

  constructor(token: string) {
    this.octokit = new Octokit({ auth: token });
  }

  async createPullRequest(
    owner: string,
    repo: string,
    head: string,
    base: string,
    title: string,
    body: string
  ): Promise<PullRequest> {
    console.log(`[GitHubVCS] Creating PR: ${owner}/${repo} ${head} -> ${base}`);

    const response = await this.octokit.pulls.create({
      owner,
      repo,
      title,
      body,
      head,
      base,
    });

    return {
      number: response.data.number,
      url: response.data.url,
      htmlUrl: response.data.html_url,
      title: response.data.title,
      body: response.data.body || '',
      head: response.data.head.ref,
      base: response.data.base.ref,
    };
  }

  getCompareUrl(owner: string, repo: string, base: string, head: string): string {
    return `https://github.com/${owner}/${repo}/compare/${base}...${head}`;
  }

  formatRepoIdentifier(owner: string, repo: string): string {
    return `${owner}/${repo}`;
  }

  async validate(): Promise<{ valid: boolean; error?: string }> {
    try {
      // Test authentication by getting user info
      await this.octokit.users.getAuthenticated();
      return { valid: true };
    } catch (error) {
      return {
        valid: false,
        error: getErrorMessage(error) || 'GitHub authentication failed',
      };
    }
  }

  /**
   * Add a comment to a pull request
   */
  async addPRComment(
    owner: string,
    repo: string,
    prNumber: number,
    body: string
  ): Promise<void> {
    await this.octokit.issues.createComment({
      owner,
      repo,
      issue_number: prNumber,
      body,
    });
  }

  /**
   * Request reviewers for a pull request
   */
  async requestReviewers(
    owner: string,
    repo: string,
    prNumber: number,
    reviewers: string[]
  ): Promise<void> {
    if (reviewers.length === 0) return;

    await this.octokit.pulls.requestReviewers({
      owner,
      repo,
      pull_number: prNumber,
      reviewers,
    });
  }

  /**
   * Add labels to a pull request
   */
  async addLabels(
    owner: string,
    repo: string,
    prNumber: number,
    labels: string[]
  ): Promise<void> {
    if (labels.length === 0) return;

    await this.octokit.issues.addLabels({
      owner,
      repo,
      issue_number: prNumber,
      labels,
    });
  }

  // ========================================
  // Plan File Operations
  // ========================================

  /**
   * Create a plan file in the repository
   * Creates a branch, commits the file, and opens a PR
   */
  async createPlanFile(
    project: VCSProjectConfig,
    content: string,
    filePath: string,
    issueNumber?: number | string
  ): Promise<PlanFileResult> {
    const { owner, repo: repoName } = this.parseRepoIdentifier(project.repoFullName);

    // Generate branch name
    const branchName = `ai-plan/${issueNumber || Date.now()}`;

    try {
      // Get default branch SHA
      const { data: repoData } = await this.octokit.repos.get({
        owner,
        repo: repoName,
      });
      const defaultBranch = repoData.default_branch;

      const { data: refData } = await this.octokit.git.getRef({
        owner,
        repo: repoName,
        ref: `heads/${defaultBranch}`,
      });
      const baseSha = refData.object.sha;

      // Create new branch
      await this.octokit.git.createRef({
        owner,
        repo: repoName,
        ref: `refs/heads/${branchName}`,
        sha: baseSha,
      });

      // Create or update the file
      await this.octokit.repos.createOrUpdateFileContents({
        owner,
        repo: repoName,
        path: filePath,
        message: `Add AI fix plan for issue #${issueNumber}`,
        content: Buffer.from(content).toString('base64'),
        branch: branchName,
      });

      // Create PR
      const prTitle = issueNumber
        ? `[AI Plan] Fix for issue #${issueNumber}`
        : `[AI Plan] Implementation plan`;

      const prBody = issueNumber
        ? `This PR contains an AI-generated implementation plan for #${issueNumber}.\n\n**Review the plan and provide feedback.** The AI will iterate based on your comments.\n\n---\n_Generated by AI Bug Fixer_`
        : `This PR contains an AI-generated implementation plan.\n\n**Review the plan and provide feedback.** The AI will iterate based on your comments.\n\n---\n_Generated by AI Bug Fixer_`;

      const { data: prData } = await this.octokit.pulls.create({
        owner,
        repo: repoName,
        title: prTitle,
        body: prBody,
        head: branchName,
        base: defaultBranch,
      });

      logger.info('Created plan file and PR', {
        owner,
        repo: repoName,
        branch: branchName,
        prNumber: prData.number,
        filePath,
      });

      // Return plan reference (use branch:filepath as reference)
      return {
        planRef: `${branchName}:${filePath}`,
        branch: branchName,
        prNumber: prData.number,
        url: prData.html_url,
      };
    } catch (error) {
      logger.error('Failed to create plan file', {
        owner,
        repo: repoName,
        error: getErrorMessage(error),
      });
      throw error;
    }
  }

  /**
   * Update an existing plan file
   */
  async updatePlanFile(
    project: VCSProjectConfig,
    planRef: string,
    content: string
  ): Promise<void> {
    const { owner, repo: repoName } = this.parseRepoIdentifier(project.repoFullName);
    const [branchName, filePath] = planRef.split(':');

    if (!branchName || !filePath) {
      throw new Error(`Invalid planRef format: ${planRef}`);
    }

    try {
      // Get current file SHA
      const { data: currentFile } = await this.octokit.repos.getContent({
        owner,
        repo: repoName,
        path: filePath,
        ref: branchName,
      });

      if (Array.isArray(currentFile) || currentFile.type !== 'file') {
        throw new Error(`Plan path is not a file: ${filePath}`);
      }

      // Update the file
      await this.octokit.repos.createOrUpdateFileContents({
        owner,
        repo: repoName,
        path: filePath,
        message: 'Update AI fix plan based on feedback',
        content: Buffer.from(content).toString('base64'),
        sha: currentFile.sha,
        branch: branchName,
      });

      logger.info('Updated plan file', {
        owner,
        repo: repoName,
        branch: branchName,
        filePath,
      });
    } catch (error) {
      logger.error('Failed to update plan file', {
        owner,
        repo: repoName,
        planRef,
        error: getErrorMessage(error),
      });
      throw error;
    }
  }

  /**
   * Get plan file content
   */
  async getPlanFile(
    project: VCSProjectConfig,
    planRef: string
  ): Promise<string | null> {
    const { owner, repo: repoName } = this.parseRepoIdentifier(project.repoFullName);
    const [branchName, filePath] = planRef.split(':');

    if (!branchName || !filePath) {
      throw new Error(`Invalid planRef format: ${planRef}`);
    }

    try {
      const { data } = await this.octokit.repos.getContent({
        owner,
        repo: repoName,
        path: filePath,
        ref: branchName,
      });

      if (Array.isArray(data) || data.type !== 'file') {
        return null;
      }

      // Decode base64 content
      return Buffer.from(data.content, 'base64').toString('utf-8');
    } catch (error: unknown) {
      // Check if it's a 404 (file not found)
      if (error && typeof error === 'object' && 'status' in error && error.status === 404) {
        return null;
      }
      throw error;
    }
  }

  /**
   * Delete/close a plan file
   * Closes the associated PR and optionally deletes the branch
   */
  async deletePlanFile(
    project: VCSProjectConfig,
    planRef: string
  ): Promise<void> {
    const { owner, repo: repoName } = this.parseRepoIdentifier(project.repoFullName);
    const [branchName] = planRef.split(':');

    if (!branchName) {
      throw new Error(`Invalid planRef format: ${planRef}`);
    }

    try {
      // Find and close any PRs from this branch
      const { data: prs } = await this.octokit.pulls.list({
        owner,
        repo: repoName,
        head: `${owner}:${branchName}`,
        state: 'open',
      });

      for (const pr of prs) {
        await this.octokit.pulls.update({
          owner,
          repo: repoName,
          pull_number: pr.number,
          state: 'closed',
        });

        logger.info('Closed plan PR', {
          owner,
          repo: repoName,
          prNumber: pr.number,
        });
      }

      // Delete the branch
      try {
        await this.octokit.git.deleteRef({
          owner,
          repo: repoName,
          ref: `heads/${branchName}`,
        });

        logger.info('Deleted plan branch', {
          owner,
          repo: repoName,
          branch: branchName,
        });
      } catch (deleteError: unknown) {
        // Branch might already be deleted
        if (deleteError && typeof deleteError === 'object' && 'status' in deleteError && deleteError.status !== 422) {
          throw deleteError;
        }
      }
    } catch (error) {
      logger.error('Failed to delete plan file', {
        owner,
        repo: repoName,
        planRef,
        error: getErrorMessage(error),
      });
      throw error;
    }
  }

  /**
   * Parse repository identifier into owner and repo
   */
  private parseRepoIdentifier(repository: string): { owner: string; repo: string } {
    const parts = repository.split('/');
    if (parts.length !== 2) {
      throw new Error(`Invalid repository identifier: ${repository}`);
    }
    return { owner: parts[0], repo: parts[1] };
  }
}
