import { AnalysisResult } from '../triggers/base';

/**
 * Pull Request data
 */
export interface PullRequest {
  number: number;
  url: string;
  htmlUrl: string;
  title: string;
  body: string;
  head: string;
  base: string;
}

/**
 * VCS plugin interface
 * Abstracts operations for different git hosting platforms
 */
export interface VCSPlugin {
  /**
   * Plugin identification
   */
  id: string;
  type: 'github' | 'gitlab' | 'bitbucket' | 'self-hosted';

  /**
   * Create a pull request
   *
   * @param owner - Repository owner/organization
   * @param repo - Repository name
   * @param head - Source branch name
   * @param base - Target branch name
   * @param title - PR title
   * @param body - PR description (markdown)
   * @returns Created pull request
   */
  createPullRequest(
    owner: string,
    repo: string,
    head: string,
    base: string,
    title: string,
    body: string
  ): Promise<PullRequest>;

  /**
   * Get compare URL for a branch (used if PR creation fails)
   */
  getCompareUrl(
    owner: string,
    repo: string,
    base: string,
    head: string
  ): string;

  /**
   * Format repository identifier for this VCS
   * e.g., "owner/repo" for GitHub, "namespace/project" for GitLab
   */
  formatRepoIdentifier(owner: string, repo: string): string;

  /**
   * Validate VCS configuration/credentials
   */
  validate(): Promise<{ valid: boolean; error?: string }>;
}

/**
 * Helper to format PR body from analysis
 */
export function formatPRBody(
  analysis: AnalysisResult,
  sourceLink: string
): string {
  return `
## Automated Fix

${sourceLink}

### Analysis

- **Root Cause:** ${analysis.rootCause}
- **Confidence:** ${analysis.confidence}
- **Complexity:** ${analysis.complexity}

### Changes

${analysis.proposedFix}

### Files Modified

${analysis.filesInvolved.map(f => `- \`${f}\``).join('\n')}

---
*This PR was automatically generated by Claude Agent. Please review carefully before merging.*
  `.trim();
}
