import { AnalysisResult } from '../triggers/base';
import type { ProjectConfig } from '../db/repositories/projects';

/**
 * Result of creating a plan file
 */
export interface PlanFileResult {
  planRef: string;         // VCS-specific reference to the plan
  branch?: string;         // Branch containing the plan (if applicable)
  prNumber?: number;       // PR number (if plan is in a PR)
  url?: string;            // Web URL to view the plan
}

/**
 * Pull Request data
 */
export interface PullRequest {
  number: number;
  url: string;
  htmlUrl: string;
  title: string;
  body: string;
  head: string;
  base: string;
}

/**
 * VCS plugin interface
 * Abstracts operations for different git hosting platforms
 */
export interface VCSPlugin {
  /**
   * Plugin identification
   */
  id: string;
  type: 'github' | 'gitlab' | 'bitbucket' | 'self-hosted';

  /**
   * Create a pull request
   *
   * @param owner - Repository owner/organization
   * @param repo - Repository name
   * @param head - Source branch name
   * @param base - Target branch name
   * @param title - PR title
   * @param body - PR description (markdown)
   * @returns Created pull request
   */
  createPullRequest(
    owner: string,
    repo: string,
    head: string,
    base: string,
    title: string,
    body: string
  ): Promise<PullRequest>;

  /**
   * Get compare URL for a branch (used if PR creation fails)
   */
  getCompareUrl(
    owner: string,
    repo: string,
    base: string,
    head: string
  ): string;

  /**
   * Format repository identifier for this VCS
   * e.g., "owner/repo" for GitHub, "namespace/project" for GitLab
   */
  formatRepoIdentifier(owner: string, repo: string): string;

  /**
   * Validate VCS configuration/credentials
   */
  validate(): Promise<{ valid: boolean; error?: string }>;

  // ========================================
  // Plan File Operations (Optional)
  // ========================================

  /**
   * Whether this VCS plugin supports plan file operations
   */
  supportsPlanFiles?: boolean;

  /**
   * Create a plan file in the repository
   * Implementation varies by VCS (branch + PR, direct file, etc.)
   *
   * @param project - Project configuration
   * @param content - Plan file content (markdown)
   * @param filePath - Path for the plan file
   * @param issueNumber - Associated issue/ticket number
   * @returns Plan reference and metadata
   */
  createPlanFile?(
    project: ProjectConfig,
    content: string,
    filePath: string,
    issueNumber?: number | string
  ): Promise<PlanFileResult>;

  /**
   * Update an existing plan file
   *
   * @param project - Project configuration
   * @param planRef - VCS-specific reference to the plan
   * @param content - Updated plan content
   */
  updatePlanFile?(
    project: ProjectConfig,
    planRef: string,
    content: string
  ): Promise<void>;

  /**
   * Get plan file content
   *
   * @param project - Project configuration
   * @param planRef - VCS-specific reference to the plan
   * @returns Plan file content or null if not found
   */
  getPlanFile?(
    project: ProjectConfig,
    planRef: string
  ): Promise<string | null>;

  /**
   * Delete/close a plan file
   * May close a PR, delete a branch, or remove the file
   *
   * @param project - Project configuration
   * @param planRef - VCS-specific reference to the plan
   */
  deletePlanFile?(
    project: ProjectConfig,
    planRef: string
  ): Promise<void>;
}

/**
 * Helper to format PR body from analysis
 */
export function formatPRBody(
  analysis: AnalysisResult,
  sourceLink: string
): string {
  return `
## Automated Fix

${sourceLink}

### Analysis

- **Root Cause:** ${analysis.rootCause}
- **Confidence:** ${analysis.confidence}
- **Complexity:** ${analysis.complexity}

### Changes

${analysis.proposedFix}

### Files Modified

${analysis.filesInvolved.map(f => `- \`${f}\``).join('\n')}

---
*This PR was automatically generated by AI Bug Fixer. Please review carefully before merging.*
  `.trim();
}
